#!/usr/bin/env ruby

require 'Qt4'
require 'qtwebkit'
require 'shellwords'

module Absorb
  Application = Qt::Application.new ARGV
  WebSettings = Qt::WebSettings.global_settings
  WebView = Qt::WebView.new

  if IO.select([$stdin], [], [], 0)
    Shellwords.shellwords($stdin.read).each &method(:require)
  end

  WebView.show
  Application.exec
end

