#!/usr/bin/env ruby

require 'Qt4'
require 'qtwebkit'
require 'xdg'

module Absorb
  Application = Qt::Application.new ARGV
  WebSettings = Qt::WebSettings.global_settings
  WebView = Qt::WebView.new

  [ Dir.glob('data/absorb/*.rb') +
    XDG::Data.glob('absorb/*.rb') ].flatten.each &method(:require)

  WebView.show
  Application.exec
end

